/bunker-hill-down-a-manhole	/2005/04/12/bunker-hill-down-a-manhole	301   
/just-duck-soup-for-vegetarian-to-land-in-city-jail	/2005/04/11/just-duck-soup-for-vegetarian-to-land-in-city-jail	301   
/in-the-soup	/2005/04/11/in-the-soup	301   
/woman-found-stabbed-to-death-in-home	/2005/04/11/woman-found-stabbed-to-death-in-home	301   
/4032-princeton-to-day	/2005/04/11/4032-princeton-to-day	301   
/sinatra-arrested-and-freed-on-bail-in-row-with-writer	/2005/04/10/sinatra-arrested-and-freed-on-bail-in-row-with-writer	301   
/ciros-to-day	/2005/04/10/ciros-to-day	301   
/crowd-perils-attack-prisoner	/2005/04/08/crowd-perils-attack-prisoner	301   
/library-park-and-the-roughly-analogous	/2005/04/08/library-park-and-the-roughly-analogous	301 